#!/bin/bash
#########################################################################
# Proxmox Hardening - Phase A Script 1
# Time Synchronization (NTP) Setup
#
# Purpose: Configure accurate time synchronization for security
#          certificates, logging, and authentication
#
# Run as: sudo bash 01-ntp-setup.sh
#########################################################################

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging
SCRIPT_DIR="/root/proxmox-hardening"
LOG_FILE="$SCRIPT_DIR/hardening.log"
BACKUP_DIR="$SCRIPT_DIR/backups"

mkdir -p "$SCRIPT_DIR" "$BACKUP_DIR"

log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
}

section() {
    echo -e "\n${BLUE}=== $1 ===${NC}\n" | tee -a "$LOG_FILE"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   error "This script must be run as root"
   echo "Please run: sudo bash $0"
   exit 1
fi

section "Time Synchronization Setup"

log "Starting NTP configuration..."
log "Accurate time is critical for SSL certificates and security logging"

# Show current time status
section "Current Time Configuration"

log "Current system time and NTP status:"
timedatectl status | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"

# Backup timesyncd configuration
section "Backing Up Configuration"

TIMESYNCD_CONF="/etc/systemd/timesyncd.conf"

if [[ -f "$TIMESYNCD_CONF" ]]; then
    backup_name="timesyncd.conf.backup.$(date +%Y%m%d_%H%M%S)"
    cp "$TIMESYNCD_CONF" "$BACKUP_DIR/$backup_name"
    log "Backed up: $TIMESYNCD_CONF -> $BACKUP_DIR/$backup_name"
fi

# Set timezone to Europe/Warsaw
section "Setting Timezone"

TIMEZONE="Europe/Warsaw"
CURRENT_TZ=$(timedatectl | grep "Time zone" | awk '{print $3}')

log "Current timezone: $CURRENT_TZ"
log "Target timezone: $TIMEZONE"

if [[ "$CURRENT_TZ" != "$TIMEZONE" ]]; then
    timedatectl set-timezone "$TIMEZONE"
    log "✓ Timezone set to $TIMEZONE"
else
    log "✓ Timezone already set to $TIMEZONE"
fi

# Configure NTP servers
section "Configuring NTP Servers"

log "Creating NTP server configuration..."

cat > "$TIMESYNCD_CONF" << 'EOF'
# NTP Configuration for Proxmox Hardening
# Generated by 01-ntp-setup.sh

[Time]
# Primary NTP servers (global pool)
NTP=0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org

# Fallback NTP servers (Europe pool)
FallbackNTP=0.europe.pool.ntp.org 1.europe.pool.ntp.org 2.europe.pool.ntp.org

# Root distance for time sync
#RootDistanceMaxSec=5

# Poll interval
#PollIntervalMinSec=32
#PollIntervalMaxSec=2048
EOF

log "✓ NTP configuration created"
log "NTP servers configured:"
echo "  - Primary: 0-3.pool.ntp.org"
echo "  - Fallback: 0-2.europe.pool.ntp.org"

# Enable NTP synchronization
section "Enabling NTP Synchronization"

log "Enabling systemd-timesyncd service..."
systemctl enable systemd-timesyncd 2>&1 | tee -a "$LOG_FILE"

log "Restarting systemd-timesyncd service..."
systemctl restart systemd-timesyncd 2>&1 | tee -a "$LOG_FILE"

log "Enabling NTP synchronization..."
timedatectl set-ntp true 2>&1 | tee -a "$LOG_FILE"

log "✓ NTP synchronization enabled"

# Wait a moment for sync to start
sleep 3

# Verify synchronization
section "Verifying Time Synchronization"

log "Current time status:"
timedatectl status | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"

log "Time synchronization details:"
timedatectl timesync-status 2>&1 | tee -a "$LOG_FILE" || log "Sync status not yet available (this is normal)"
echo "" | tee -a "$LOG_FILE"

log "systemd-timesyncd service status:"
systemctl status systemd-timesyncd --no-pager | tee -a "$LOG_FILE"

# Check if NTP is active
NTP_ACTIVE=$(timedatectl | grep "NTP service" | awk '{print $3}')

if [[ "$NTP_ACTIVE" == "active" ]]; then
    log "✓ NTP service is active and running"
else
    warn "NTP service may not be fully active yet"
    warn "This can take a few minutes - check status with: timedatectl status"
fi

# Summary
section "Time Synchronization Complete"

echo ""
log "✓ Timezone set to $TIMEZONE"
log "✓ NTP servers configured (pool.ntp.org)"
log "✓ systemd-timesyncd enabled and running"
log "✓ NTP synchronization active"
echo ""

warn "Note: It may take a few minutes for time to fully synchronize"
warn "You can monitor sync status with: timedatectl timesync-status"
echo ""

log "Current date/time: $(date)"
echo ""

log "Backup saved to: $BACKUP_DIR"
log "Script completed successfully!"

# Rollback instructions
section "Rollback Instructions"

cat << EOF
If you need to rollback this configuration:

1. Restore original timesyncd configuration:
   sudo cp $BACKUP_DIR/timesyncd.conf.backup.* /etc/systemd/timesyncd.conf

2. Restart timesyncd service:
   sudo systemctl restart systemd-timesyncd

3. Optionally, change timezone back:
   sudo timedatectl set-timezone <your-timezone>

Check available timezones:
   timedatectl list-timezones

EOF

exit 0
