#!/bin/bash
#########################################################################
# Proxmox Hardening - Phase C Script 11
# Fail2ban Setup - Brute Force Protection
#
# Purpose: Configure fail2ban to protect SSH and Proxmox Web UI
#          from brute-force attacks
#
# Run as: sudo bash 11-fail2ban-setup.sh
#########################################################################

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="/root/proxmox-hardening"
LOG_FILE="$SCRIPT_DIR/hardening.log"
BACKUP_DIR="$SCRIPT_DIR/backups/fail2ban"

TRUSTED_IP="192.168.99.6"
SSH_PORT="22022"

# Logging functions
log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
}

section() {
    echo -e "\n${BLUE}=== $1 ===${NC}\n" | tee -a "$LOG_FILE"
}

info() {
    echo -e "${CYAN}[INFO]${NC} $1"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   error "This script must be run as root"
   echo "Please run: sudo bash $0"
   exit 1
fi

section "Fail2ban Setup - Phase C Script 11"

log "Starting fail2ban configuration..."

# Create backup directory
mkdir -p "$BACKUP_DIR"

# ===========================================
# Step 1: Check if fail2ban is installed
# ===========================================
section "Step 1: Verify Fail2ban Installation"

if dpkg -l | grep -q "^ii.*fail2ban"; then
    log "✓ Fail2ban already installed"
    FAIL2BAN_VERSION=$(fail2ban-client version | head -1)
    info "  Version: $FAIL2BAN_VERSION"
else
    log "Installing fail2ban..."
    apt update
    apt install -y fail2ban
    log "✓ Fail2ban installed"
fi

# ===========================================
# Step 2: Backup existing configuration
# ===========================================
section "Step 2: Backup Existing Configuration"

if [ -f /etc/fail2ban/jail.local ]; then
    backup_name="jail.local.backup.$(date +%Y%m%d_%H%M%S)"
    cp /etc/fail2ban/jail.local "$BACKUP_DIR/$backup_name"
    log "Backed up existing jail.local: $backup_name"
fi

if [ -d /etc/fail2ban/filter.d ]; then
    if [ ! -d "$BACKUP_DIR/filter.d" ]; then
        mkdir -p "$BACKUP_DIR/filter.d"
    fi
    cp -r /etc/fail2ban/filter.d/* "$BACKUP_DIR/filter.d/" 2>/dev/null || true
    log "Backed up filter.d directory"
fi

# ===========================================
# Step 3: Create Proxmox Filter
# ===========================================
section "Step 3: Create Proxmox Web UI Filter"

cat > /etc/fail2ban/filter.d/proxmox.conf << 'EOF'
# Fail2ban filter for Proxmox VE Web UI
#
# Detects failed authentication attempts to Proxmox web interface

[Definition]

# Match failed login attempts in systemd journal (pvedaemon)
# Format: authentication failure; rhost=::ffff:192.168.x.x user=username@realm msg=...
failregex = ^.*pvedaemon\[.*\]: authentication failure; rhost=(:?:ffff:)?<HOST> user=.* msg=.*$

# Ignore successful logins
ignoreregex = ^.*pvedaemon\[.*\]: <.*> successful auth for user.*$

# Author: Proxmox Hardening Script
EOF

log "✓ Created Proxmox filter: /etc/fail2ban/filter.d/proxmox.conf"

# ===========================================
# Step 4: Create jail.local Configuration
# ===========================================
section "Step 4: Configure Fail2ban Jails"

cat > /etc/fail2ban/jail.local << EOF
#
# Fail2ban Configuration for Proxmox
# Generated by Proxmox Hardening Script
# Date: $(date)
#

[DEFAULT]
# Ban settings
bantime  = 3600         # Ban for 1 hour
findtime = 600          # Within 10 minutes
maxretry = 3            # After 3 failed attempts

# Ignore trusted IPs (never ban these)
ignoreip = 127.0.0.1/8 ::1 $TRUSTED_IP

# Ban action (use iptables)
banaction = iptables-multiport
banaction_allports = iptables-allports

# Email settings (disabled - using ntfy.sh instead)
destemail = root@localhost
sender = fail2ban@proxmox
mta = sendmail

# Action when ban occurs
# For now just ban, later we'll add ntfy notifications
action = %(action_)s

# ============================================
# SSH Protection (Port $SSH_PORT)
# ============================================
[sshd]
enabled  = true
port     = $SSH_PORT
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 3
bantime  = 7200         # Ban for 2 hours for SSH
findtime = 600

# ============================================
# Proxmox Web UI Protection (Port 8006)
# ============================================
[proxmox]
enabled  = true
port     = https,http,8006
filter   = proxmox
backend  = systemd
journalmatch = _SYSTEMD_UNIT=pvedaemon.service
maxretry = 3
bantime  = 3600         # Ban for 1 hour
findtime = 600

# ============================================
# Additional Protection (Optional)
# ============================================

# Aggressive SSH protection (optional)
[sshd-aggressive]
enabled  = false
port     = $SSH_PORT
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 2
bantime  = 86400        # Ban for 24 hours
findtime = 300

EOF

log "✓ Created jail configuration: /etc/fail2ban/jail.local"

# ===========================================
# Step 5: Test Configuration
# ===========================================
section "Step 5: Test Fail2ban Configuration"

log "Testing fail2ban configuration..."

if fail2ban-client -t; then
    log "✓ Configuration test passed"
else
    error "Configuration test failed!"
    error "Please check the configuration files"
    exit 1
fi

# ===========================================
# Step 6: Enable and Start Fail2ban
# ===========================================
section "Step 6: Enable and Start Fail2ban"

log "Restarting fail2ban service..."
systemctl enable fail2ban
systemctl restart fail2ban

# Wait a moment for service to start
sleep 2

if systemctl is-active --quiet fail2ban; then
    log "✓ Fail2ban service is running"
else
    error "Fail2ban service failed to start!"
    error "Check status: systemctl status fail2ban"
    exit 1
fi

# ===========================================
# Step 7: Verify Jails are Active
# ===========================================
section "Step 7: Verify Active Jails"

log "Checking active jails..."

# Get jail status
JAIL_STATUS=$(fail2ban-client status 2>/dev/null || echo "")

if echo "$JAIL_STATUS" | grep -q "sshd"; then
    log "✓ SSH jail is active"
else
    warn "SSH jail is NOT active"
fi

if echo "$JAIL_STATUS" | grep -q "proxmox"; then
    log "✓ Proxmox jail is active"
else
    warn "Proxmox jail is NOT active"
fi

# ===========================================
# Step 8: Display Current Status
# ===========================================
section "Step 8: Fail2ban Status"

echo ""
echo "=========================================="
echo "FAIL2BAN STATUS"
echo "=========================================="
echo ""

fail2ban-client status

echo ""
echo "SSH Jail Details:"
echo "----------------------------------------"
fail2ban-client status sshd 2>/dev/null || echo "SSH jail not found"

echo ""
echo "Proxmox Jail Details:"
echo "----------------------------------------"
fail2ban-client status proxmox 2>/dev/null || echo "Proxmox jail not found"

# ===========================================
# Summary
# ===========================================
section "Fail2ban Setup Complete"

echo ""
log "Configuration Summary:"
echo "  • Trusted IP (never banned): $TRUSTED_IP"
echo "  • SSH jail: Port $SSH_PORT, max 3 retries, 2 hour ban"
echo "  • Proxmox jail: Port 8006, max 3 retries, 1 hour ban"
echo "  • Logs: /var/log/fail2ban.log"
echo ""

log "Useful commands:"
echo "  • Check status:        fail2ban-client status"
echo "  • Check SSH jail:      fail2ban-client status sshd"
echo "  • Check Proxmox jail:  fail2ban-client status proxmox"
echo "  • Unban an IP:         fail2ban-client set sshd unbanip <IP>"
echo "  • View banned IPs:     fail2ban-client status sshd"
echo "  • View logs:           tail -f /var/log/fail2ban.log"
echo ""

log "Backups saved to: $BACKUP_DIR"
echo ""

warn "Important Notes:"
echo "  • Your IP ($TRUSTED_IP) will NEVER be banned"
echo "  • Failed login attempts are logged in /var/log/fail2ban.log"
echo "  • Bans are automatically removed after ban time expires"
echo "  • You can manually unban IPs if needed"
echo ""

log "Script 11 completed successfully!"
log "Next: Run 12-notification-setup.sh to configure security alerts"

exit 0
